In [1]:
import numpy as np

In [ ]:
#NumPy (Numerical Python), Python'da büyük, çok boyutlu diziler (arrays) ve matrislerle çalışmak için kullanılan ana kütüphanedir.

In [2]:
my_list = [10,20,30,40]

In [3]:
type(my_list)

list

In [4]:
np.array(my_list)

array([10, 20, 30, 40])

In [5]:
my_numpy_array = np.array(my_list)

In [6]:
type(my_numpy_array)

numpy.ndarray

In [7]:
my_numpy_array.max()

np.int64(40)

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.random.random(5)

array([0.91945014, 0.18021272, 0.66947106, 0.16841792, 0.18163202])

In [11]:
# array arithmetic

In [12]:
my_list1 = [1,2]

In [13]:
my_list2 = [2,3]

In [14]:
my_list1 + my_list2

[1, 2, 2, 3]

In [15]:
my_numpy_array1 = np.array(my_list1)

In [16]:
my_numpy_array2 = np.array(my_list2)

In [17]:
my_numpy_array1 + my_numpy_array2

array([3, 5])

In [18]:
my_numpy_array1 * my_numpy_array2

array([2, 6])

In [19]:
my_numpy_array1 - my_numpy_array2

array([-1, -1])

In [20]:
my_numpy_array1 / my_numpy_array2

array([0.5       , 0.66666667])

In [21]:
my_numpy_array1 * 5

array([ 5, 10])

In [22]:
my_list1 * 5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [23]:
other_array = np.array([10,20,30,40,50])

In [24]:
other_array.min()

np.int64(10)

In [25]:
other_array.sum()

np.int64(150)

In [26]:
my_numpy_array1

array([1, 2])

In [27]:
other_array

array([10, 20, 30, 40, 50])

In [28]:
#my_numpy_array1 + other_array

In [29]:
# arange & indexing

In [31]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [33]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [35]:
np_array = np.arange(0,10)

In [36]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np_array[0]

np.int64(0)

In [38]:
np_array[-1]

np.int64(9)

In [39]:
np_array[1:4:]

array([1, 2, 3])

In [40]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [41]:
np_array[2:6:2]

array([2, 4])

In [42]:
# random

In [43]:
np.random.randn(4)

array([-1.34656601,  1.04104961, -0.83654519, -0.82204324])

In [44]:
np.random.randn(4,4)

array([[ 0.74853084, -0.47028754, -0.30129543, -0.77761776],
       [-1.08210267, -1.46628951,  0.93827421,  0.90712969],
       [ 0.08796924,  0.53861318, -1.20281226, -0.01271875],
       [ 1.03486399, -0.19075258,  0.46836917, -0.15994733]])

In [45]:
np.random.randint(1,300,5)

array([218, 270,  17,  15, 103], dtype=int32)