In [1]:
import numpy as np

In [2]:
new_array = np.random.randint(1,100,20)

In [3]:
new_array

array([65, 70, 21, 33, 70, 91, 18, 66, 56, 25, 57, 74, 61, 88, 44, 96,  7,
       62, 56, 97], dtype=int32)

In [4]:
new_array>25

array([ True,  True, False,  True,  True,  True, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True])

In [5]:
new_array[new_array>25]

array([65, 70, 33, 70, 91, 66, 56, 57, 74, 61, 88, 44, 96, 62, 56, 97],
      dtype=int32)

In [6]:
new_array[new_array<25]

array([21, 18,  7], dtype=int32)

In [7]:
# transpose & reshape

In [10]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [11]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [12]:
matrix_array.shape

(3, 2)

In [13]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [14]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [15]:
random_array = np.random.random((6,1))

In [16]:
random_array

array([[0.01687904],
       [0.97530268],
       [0.29058165],
       [0.43973586],
       [0.89038043],
       [0.14278629]])

In [17]:
random_array.shape

(6, 1)

In [18]:
random_array.reshape(2,3)

array([[0.01687904, 0.97530268, 0.29058165],
       [0.43973586, 0.89038043, 0.14278629]])

In [19]:
random_array.reshape(3,2)

array([[0.01687904, 0.97530268],
       [0.29058165, 0.43973586],
       [0.89038043, 0.14278629]])

In [20]:
# z-score

In [21]:
data = np.array([10,12,13,15,18,25,100,105])

In [22]:
#outlier

In [23]:
mean = np.mean(data)

In [24]:
mean

np.float64(37.25)

In [25]:
data.sum() / len(data)

np.float64(37.25)

In [26]:
std = np.std(data)

In [27]:
std

np.float64(37.9333296719389)

In [28]:
z_scores = (data - mean) / std

In [29]:
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [31]:
data[z_scores>1]

array([100, 105])

In [32]:
#math equations

In [33]:
# 2x + 3y = 8 and 5x + 7y = 19

In [34]:
#coefficient

In [35]:
A = np.array([[2,3],[5,7]])

In [36]:
#constant

In [37]:
b = np.array([8,19])

In [38]:
solution = np.linalg.solve(A,b)

In [ ]:
soluti